import Head from "next/head";
import { Inter } from "@next/font/google";
import {
  Box,
  Button,
  Card,
  CardBody,
  Center,
  Container,
  Flex,
  Heading,
  Stack,
  Text,
  Image,
  Accordion,
  AccordionButton,
  AccordionIcon,
  AccordionItem,
  AccordionPanel,
} from "@chakra-ui/react";
import { useState } from "react";
import { SavedTracksData } from "@/types";
import { NextPage } from "next";
import { AppProps } from "next/app";
import Cluster from "./cluster";

const inter = Inter({ subsets: ["latin"] });

export type NextApplicationPage<P = any, IP = P> = NextPage<P, IP> & {
  requireAuth?: boolean;
};

export default function Home(props: AppProps) {
  const {
    Component,
    pageProps,
  }: { Component: NextApplicationPage; pageProps: any } = props;

  return (
    <>
      <Head>
        <title>Splitify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container maxWidth="100%" background={"blackAlpha.100"}>
          <Cluster />
        </Container>
      </main>
    </>
  );
}
