import { Center, Container } from "@chakra-ui/react";
import { NextPage } from "next";
import { AppProps } from "next/app";
import Head from "next/head";

import Login from "./auth/Login";

export type NextApplicationPage<P = any, IP = P> = NextPage<P, IP> & {
  requireAuth?: boolean;
};

export default function Home(props: AppProps) {
  return (
    <>
      <Head>
        <title>Splitify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container maxHeight="100%">
          <Center>
            <Login />
          </Center>
        </Container>
      </main>
    </>
  );
}
